from __future__ import annotations

from typing import Any, Protocol


class JobsRepoPort(Protocol):
    def get_job(self, job_id: str) -> dict[str, Any] | None: ...
    def list_jobs(self, *, limit: int, offset: int) -> list[dict[str, Any]]: ...
    def list_job_events(
        self, job_id: str, *, limit: int, offset: int
    ) -> list[dict[str, Any]]: ...
    def get_job_run(self, job_id: str) -> dict[str, Any] | None: ...
